### ISSUE TITLE
Incompatible with version 1.21.21

### ISSUE THREAD

**Issue by Sushi402** [vytdev/debug-stick#4]
Debug stick doesn't function with Minecraft: Bedrock Edition version 1.21.22

**Comment by vytdev** [comment]
Sorry I forgot to update it. I just got busy in school.

**Comment by vytdev** [comment]
Now updated!

https://github.com/vytdev/debug-stick/releases/tag/v1.10.0


Haven't tested it yet with 1.20.21, but it seems to work pretty well in 1.20.23. If the issue persists, please let me know. You can re-open this issue at any time!
