### ISSUE TITLE
Issues to resolve (and make the addon use Stable APIs)

### ISSUE THREAD

**Issue by Assassin1065** [vytdev/debug-stick#5]
1. edit Manifest.json and use :
        `{
			"module_name": "@minecraft/server-ui",
			"version": "1.1.0"
	  },
	  {
			"module_name": "@minecraft/server",
			"version": "1.13.0"
	  }`
2. Add the component `"minecraft:hand_equipped": true,` to the debug stick item.
3. Edit the displayBlockInfo function. 
```js
function displayBlockInfo(player, block) {
    let info = "§l§b" + block.typeId + "§r";
    info += "\n§4" + block.x + " §a" + block.y + " §9" + block.z;
    info += "\n§7matter state§8: §e";
    if (block.isLiquid) info += "liquid";
    else if (block.isAir) info += "gas";
    else info += "solid";
    info += "\n§7hard block§8: " + (block.isSolid ? "§ayes" : "§cno");
    // Retrieve and display the block states/properties
    Object.entries(block.permutation.getAllStates()).forEach(([k, v]) => {
        info += "\n§o§7" + k + "§r§8: ";
        if (typeof v == "string") info += "§e";
        if (typeof v == "number") info += "§3";
        if (typeof v == "boolean") info += "§6";
        info += v;
    });
    // Check if the block type can be waterlogged and display the status
    if (block.type.canBeWaterlogged) info += "\n§o§7waterlogged§r§8: §6" + block.isWaterlogged;
    // Display block tags if available
    if (block.tags) {
        block.tags.forEach(tag => info += "\n§d#" + tag);
    }
    // Show the message to the player
    message(info, player);
}```

**Comment by vytdev** [comment]
Ohh interesting... I'll check it.

#6
#7
#8

**Comment by Assassin1065** [comment]
Turns out server-ui isnt needed.

**Comment by vytdev** [comment]
hey @Assassin1065

thanks a bunch for all the work you put into the PRs and trying to get the addon working with the stable API. seriously, it means a lot, and I really appreciate the effort…

but, after going through the changes and running the tests, I noticed some key stuff like:

- `BlockType.canBeWaterlogged`
- `Block.isWaterlogged`
- `Block.setWaterlogged()`
- `Block.isSolid`
- `Block.getRedstonePower()`

aren't available yet in the stable API version you set (1.13.0). these are pretty important for the addon, and without them, some core features won’t work right :/

also, while the code looks good overall, the CI tests ended up failing 'cause of these missing features. additionally, we don't need `@minecraft/server-ui` for the debug stick to work

so yeah, with that in mind, I’m gonna have to close the PRs and mark the issue as "*wontfix*" for now... but once those features are supported in the stable API, we can totally revisit it

thanks again for all your contributions! really hope to see more from you down the road :)

**Comment by vytdev** [comment]
just let me know if there's anything we can improve! i'm also waiting for the game's API to be fully stable, but there are still a few things the addon needs to work around for now

**Comment by Assassin1065** [comment]
Gotcha. Those will still work with beta apis. I prefer working without beta apis so I overlooked these.

I still think you should push some sort of update to this.

**Comment by Assassin1065** [comment]
Also adding the "minecraft:hand_equipped" component to the debug stick item will make it render just like a tool when held in hand, just like it does in java, and it would match the vanilla stick.

**Comment by vytdev** [comment]
> Also adding the "minecraft:hand_equipped" component to the debug stick item will make it render just like a tool when held in hand, just like it does in java, and it would match the vanilla stick.

ohh, sorry I didn’t notice that I closed that separate PR. i will go ahead and reopen it and do some checks

**Comment by vytdev** [comment]
rebased and merged #8

**Comment by vytdev** [comment]
should I release a new patch now to accommodate the changes, or would you prefer to wait for a later update?

**Comment by vytdev** [comment]
just experimenting with github comments. ignore me

https://github.com/vytdev/debug-stick/blob/b5bfff1f392715d346cb617d0279e4146154e183/src/index.ts#L159-L185

**Comment by vytdev** [comment]
@Assassin1065, I had:

1. Merged your PR regarding the `minecraft:hand_equipped` addition
2. Released a patch update here in this repo
3. mcpedl is pending update approval (you're recognized there!)

\* *also i've seen your email*

**Comment by Assassin1065** [comment]
Thanks! I couldn't find any discord or other social media.

I just didnt want to see this abandoned lol.

**Comment by Assassin1065** [comment]
Also yeah. I post a lot on mcpedl lol
